export const membersData = [
  {
    email: "nimbus@test.com",
    username: "nimbus",
    gender: "female",
    dateOfBirth: "1986-07-22",
    name: "Nimbus",
    created: "2020-06-24",
    lastActive: "2020-06-21",
    description: "A mystical cat with gentle purrs and curious eyes.",
    city: "Springfield",
    country: "USA",
    image: "/images/user1.jpg",
  },
  {
    email: "mochi@test.com",
    username: "mochi",
    gender: "female",
    dateOfBirth: "1995-10-12",
    name: "Mochi",
    created: "2019-12-09",
    lastActive: "2020-05-06",
    description: "Soft and sweet, this kitty is as delightful as its name.",
    city: "Toronto",
    country: "Canada",
    image: "/images/user2.jpg",
  },
  {
    email: "pippin@test.com",
    username: "pippin",
    gender: "female",
    dateOfBirth: "1989-01-24",
    name: "Pippin",
    created: "2019-08-10",
    lastActive: "2020-05-12",
    description: "Adventurous and mischievous, always chasing playful shadows.",
    city: "Paris",
    country: "France",
    image: "/images/user3.jpg",
  },
  {
    email: "taffy@test.com",
    username: "taffy",
    gender: "female",
    dateOfBirth: "1988-06-22",
    name: "Taffy",
    created: "2019-04-24",
    lastActive: "2020-06-17",
    description: "Stretchy and sweet, a true bundle of feline energy.",
    city: "Berlin",
    country: "Germany",
    image: "/images/user4.jpg",
  },
  {
    email: "jinx@test.com",
    username: "jinx",
    gender: "female",
    dateOfBirth: "1986-01-12",
    name: "Jinx",
    created: "2019-04-30",
    lastActive: "2020-06-21",
    description: "Quirky and playful, always ready to spark a little mischief.",
    city: "Rio de Janeiro",
    country: "Brazil",
    image: "/images/user5.jpg",
  },
  {
    email: "clover@test.com",
    username: "clover",
    gender: "male",
    dateOfBirth: "1980-02-07",
    name: "Clover",
    created: "2019-04-29",
    lastActive: "2020-05-16",
    description: "Lucky and charming, bringing a touch of magic every day.",
    city: "Tokyo",
    country: "Japan",
    image: "/images/user6.jpg",
  },
  {
    email: "miso@test.com",
    username: "miso",
    gender: "male",
    dateOfBirth: "1997-04-09",
    name: "Miso",
    created: "2020-04-05",
    lastActive: "2020-06-23",
    description: "A refined little feline with a delightful taste for mischief.",
    city: "Sydney",
    country: "Australia",
    image: "/images/user7.jpg",
  },
  {
    email: "whiskers@test.com",
    username: "whiskers",
    gender: "male",
    dateOfBirth: "1990-03-23",
    name: "Whiskers",
    created: "2020-03-14",
    lastActive: "2020-05-17",
    description: "Classic charm with endless curiosity and adorable whiskers.",
    city: "Madrid",
    country: "Spain",
    image: "/images/user8.jpg",
  },
  {
    email: "pixel@test.com",
    username: "pixel",
    gender: "male",
    dateOfBirth: "1982-12-01",
    name: "Pixel",
    created: "2019-01-28",
    lastActive: "2020-06-07",
    description: "Tiny and digital in spirit, with a purrfect pixelated charm.",
    city: "Milan",
    country: "Italy",
    image: "/images/user9.jpg",
  },
  {
    email: "pudding@test.com",
    username: "pudding",
    gender: "male",
    dateOfBirth: "1978-03-20",
    name: "Pudding",
    created: "2020-02-25",
    lastActive: "2020-06-11",
    description: "Smooth and comforting, as sweet as your favorite dessert.",
    city: "London",
    country: "UK",
    image: "/images/user10.jpg",
  },
];
